package com.dizzycode.dizzycode.mock.category;

import com.dizzycode.dizzycode.category.domain.Category;
import com.dizzycode.dizzycode.category.domain.dto.CategoryDetailDTO;
import com.dizzycode.dizzycode.category.service.port.CategoryRepository;
import com.dizzycode.dizzycode.room.domain.Room;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

public class FakeCategoryRepository implements CategoryRepository {

    private Long autoGeneratedId = 0L;
    private final List<Category> data = new ArrayList<>();

    @Override
    public List<CategoryDetailDTO> findCategoriesByRoom(Long roomId) {
        return data.stream()
                .filter(c -> c.getRoom().getRoomId().equals(roomId))
                .map(c -> {
                    CategoryDetailDTO dto = new CategoryDetailDTO();
                    dto.setCategoryId(c.getCategoryId());
                    dto.setCategoryName(c.getCategoryName());
                    dto.setRoomId(roomId);
                    dto.setChannels(new ArrayList<>());
                    return dto;
                })
                .collect(Collectors.toList());
    }

    @Override
    public Optional<Category> findCategoryByCategoryId(Long categoryId) {
        return data.stream().filter(c -> c.getCategoryId().equals(categoryId)).findFirst();
    }

    @Override
    public Category save(Long roomId, String categoryName) {
        Room room = Room.builder().roomId(roomId).roomName("testRoom").open(true).build();
        Category category = Category.builder()
                .categoryId(++autoGeneratedId)
                .room(room)
                .categoryName(categoryName)
                .channels(new ArrayList<>())
                .build();
        data.add(category);
        return category;
    }
}
