package com.dizzycode.dizzycode.mock.channel;

import com.dizzycode.dizzycode.category.domain.Category;
import com.dizzycode.dizzycode.channel.domain.Channel;
import com.dizzycode.dizzycode.channel.domain.dto.ChannelCreateDTO;
import com.dizzycode.dizzycode.channel.service.port.ChannelRepository;
import com.dizzycode.dizzycode.mock.category.FakeCategoryRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

public class FakeChannelRepository implements ChannelRepository {

    private Long autoGeneratedId = 0L;
    private final List<Channel> data = new ArrayList<>();
    private final FakeCategoryRepository categoryRepository;

    public FakeChannelRepository(FakeCategoryRepository categoryRepository) {
        this.categoryRepository = categoryRepository;
    }

    @Override
    public List<Channel> findChannelsByCategory(Category category) {
        return data.stream()
                .filter(c -> c.getCategory().getCategoryId().equals(category.getCategoryId()))
                .collect(Collectors.toList());
    }

    @Override
    public Optional<Channel> findChannelByChannelId(Long channelId) {
        return data.stream().filter(c -> c.getChannelId().equals(channelId)).findFirst();
    }

    @Override
    public Channel save(Long categoryId, ChannelCreateDTO channelCreateDTO) {
        Category category = categoryRepository.findCategoryByCategoryId(categoryId).orElseThrow();
        Channel channel = Channel.builder()
                .channelId(++autoGeneratedId)
                .category(category)
                .channelName(channelCreateDTO.getChannelName())
                .channelType(channelCreateDTO.getChannelType())
                .build();
        data.add(channel);
        return channel;
    }
}
